puppycompanyblog/models.py
import datetime

from puppycompanyblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):

    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(64), nullable=False, default='default.png')
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(20), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost', backref="author", lazy=True)

    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"Username: {self.username}"


class BlogPost(db.Model):

    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey(users.id), nullable=False, default=datetime.utcnow())
    date = db.Column(db.DateTime, nullable=False)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self, title, text, user_id):
        self.title = title
        self.text = text
        self.id = user_id

    def __repr__(self):
        return f"Post ID: {self.id} Title: {self.title}"

puppycompanyblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField

puppycompanyblog/__init__.py
# pupyycompanyblog/__init__.py

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from puppycompanyblog.core.views import core
from puppycompanyblog.error_pages.handlers import error_pages

app = Flask(__name__)

# Database setup
db = SQLAlchemy(app)
Migrate(db, app)
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite://"+os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# Blueprints
app.register_blueprint(core)
app.register_blueprint(error_pages)

# login
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

puppycompanyblog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

puppycompanyblog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</head>
<body>
    <ul class="nav">
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Home</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.info') }}">About</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Log Out</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Account</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Create Post</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Log In</a>
        </li>
        <li class="nav-link">
            <a href="{{ url_for('core.index') }}">Register</a>
        </li>
    </ul>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

puppycompanyblog/templates/index.html
{% extends "base.html"%}
{% block content %}
    <div class="jumbotron">
    <h1>Puppy Company Blog</h1>
    </div>
{% endblock %}

ß

puppycompanyblog/templates/info.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
    <h1>Company Info</h1>
        <p>alsdkjfapksdjfpas</p>
    </div>
{% endblock %}